title: Zyyz - Personal blog
url: "https://0xzyyz.github.io"
baseurl: ""

author:
  name: Mohamed Aziz Rahmouni
  github: 0xZyyz

permalink: /:title/
markdown: kramdown
timezone: Africa/Tunis

exclude:
  - README.md
  - vendor
  - .bundle