title: Zyyz - Personal blog
url: "https://zyyz2.github.io"
baseurl: ""

author:
  name: Mohamed Aziz Rahmouni
  github: Zyyz2

permalink: /:title/
markdown: kramdown
timezone: Africa/Tunis

exclude:
  - README.md
  - vendor
  - .bundle